src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use App\Entity\Voiture;
use App\Entity\Preference;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'users')]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'Cet email est déjà utilisé.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "IDENTITY")]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[Assert\NotBlank(message: "L'adresse email est obligatoire.")]
    #[Assert\Email(message: "Veuillez saisir une adresse email valide.")]
    #[ORM\Column(length: 180)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    #[Assert\NotBlank(message: "Le mot de passe est obligatoire.")]
    #[Assert\Length(min: 8, minMessage: "Le mot de passe doit contenir au moins 8 caractères.")]
    #[Assert\Regex(
        pattern: "/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).+$/",
        message: "Le mot de passe doit contenir au moins une majuscule, une minuscule, un  caractère spécial et un chiffre."
    )]
    #[ORM\Column]
    private ?string $password = null;

    #[Assert\NotBlank(message: "Le nom est obligatoire.")]
    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[Assert\NotBlank(message: "Le prénom est obligatoire.")]
    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[Assert\NotBlank(message: "Le numéro de téléphone est obligatoire.")]
    #[Assert\Length(min: 10, minMessage: "Le numéro doit contenir au moins 10 chiffres.")]
    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[Assert\NotBlank(message: "L'adresse est obligatoire.")]
    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[Assert\NotNull(message: "La date de naissance est obligatoire.")]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_naissance = null;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private $photo = null;

    #[Assert\NotBlank(message: "Le pseudo est obligatoire.")]
    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isSuspended = false;

    #[ORM\Column(type: 'boolean')]
    private bool $isChauffeur = false;

    #[ORM\Column(type: 'boolean')]
    private bool $isPassager = true;


    #[ORM\Column(type: 'float', nullable: true)]
    private ?float $note = null;

    #[ORM\Column(type: 'integer')]
    private int $credits = 20;

    #[ORM\OneToMany(mappedBy: 'conducteur', targetEntity: Avis::class)]
    private Collection $avisConducteur;



    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Voiture::class, cascade: ['persist', 'remove'])]
    private Collection $voitures;

    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'user')]
    private Collection $avis;

    /**
     * @var Collection<int, \App\Entity\Covoiturage>
     */

    #[ORM\OneToMany(mappedBy: 'conducteur', targetEntity: Covoiturage::class)]
    private Collection $covoituragesConduits;

    /**
     * @var Collection<int, \App\Entity\Covoiturage>
     */
    #[ORM\ManyToMany(targetEntity: Covoiturage::class, mappedBy: 'passagers')]
    private Collection $covoituragesEnPassager;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Preference $preference = null;

    public function __construct()
    {
        $this->voitures = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->covoituragesConduits = new ArrayCollection();
        $this->covoituragesEnPassager = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    public function eraseCredentials(): void {}

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;
        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;
        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;
        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;
        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getPhoto(): ?string
    {
        if ($this->photo === null) {
            return null;
        }

        // Vérifie que la ressource est encore ouverte
        if (is_resource($this->photo)) {
            rewind($this->photo); // très important pour éviter de lire à la fin
            return base64_encode(stream_get_contents($this->photo));
        }

        return $this->photo;
    }

    public function setPhoto($photo): static
    {
        $this->photo = $photo;
        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;
        return $this;
    }

    public function isChauffeur(): bool
    {
        return $this->isChauffeur;
    }

    public function setIsChauffeur(bool $isChauffeur): static
    {
        $this->isChauffeur = $isChauffeur;
        return $this;
    }

    public function isPassager(): bool
    {
        return $this->isPassager;
    }

    public function setIsPassager(bool $isPassager): static
    {
        $this->isPassager = $isPassager;
        return $this;
    }





    public function getCredits(): int
    {
        return $this->credits;
    }

    public function setCredits(int $credits): static
    {
        $this->credits = $credits;
        return $this;
    }



    /**
     * @return Collection<int, \App\Entity\Voiture>
     */

    public function getVoitures(): Collection
    {
        return $this->voitures;
    }

    public function addVoiture(Voiture $voiture): static
    {
        if (!$this->voitures->contains($voiture)) {
            $this->voitures->add($voiture);
            $voiture->setUser($this);
        }

        return $this;
    }

    public function removeVoiture(Voiture $voiture): static
    {
        if ($this->voitures->removeElement($voiture)) {
            if ($voiture->getUser() === $this) {
                $voiture->setUser(null);
            }
        }

        return $this;
    }

    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setUser($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            if ($avi->getUser() === $this) {
                $avi->setUser(null);
            }
        }

        return $this;
    }

    public function getCovoituragesConduits(): Collection
    {
        return $this->covoituragesConduits;
    }

    public function getCovoituragesEnPassager(): Collection
    {
        return $this->covoituragesEnPassager;
    }

    public function addCovoituragesEnPassager(Covoiturage $covoiturage): static
    {
        if (!$this->covoituragesEnPassager->contains($covoiturage)) {
            $this->covoituragesEnPassager->add($covoiturage);
            $covoiturage->addPassager($this);
        }

        return $this;
    }

    public function removeCovoituragesEnPassager(Covoiturage $covoiturage): static
    {
        if ($this->covoituragesEnPassager->removeElement($covoiturage)) {
            $covoiturage->removePassager($this);
        }

        return $this;
    }

    public function getPreference(): ?Preference
    {
        return $this->preference;
    }

    public function setPreference(?Preference $preference): static
    {

        if ($preference && $preference->getUser() !== $this) {
            $preference->setUser($this);
        }

        $this->preference = $preference;
        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvisConducteur(): Collection
    {

src/Entity/Voiture.php
<?php

namespace App\Entity;

use App\Repository\VoitureRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VoitureRepository::class)]
class Voiture
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: "IDENTITY")]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $immatriculation = null;

    #[ORM\Column(length: 255)]
    private ?string $couleur = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_premiere_immatriculation = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $ecologique = false;

    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $nb_place = null;

    #[ORM\ManyToOne(inversedBy: 'voitures')]
    private ?User $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $energie = null;

    /**
     * @var Collection<int, Covoiturage>
     */
    #[ORM\OneToMany(targetEntity: Covoiturage::class, mappedBy: 'voiture')]
    private Collection $covoiturages;

    public function __construct()
    {
        $this->covoiturages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;
        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;
        return $this;
    }

    public function getImmatriculation(): ?string
    {
        return $this->immatriculation;
    }

    public function setImmatriculation(string $immatriculation): static
    {
        $this->immatriculation = $immatriculation;
        return $this;
    }

    public function getEnergie(): ?string
    {
        return $this->energie;
    }

    public function setEnergie(string $energie): static
    {
        $this->energie = $energie;
        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): static
    {
        $this->couleur = $couleur;
        return $this;
    }

    public function getDatePremiereImmatriculation(): ?\DateTimeInterface
    {
        return $this->date_premiere_immatriculation;
    }

    public function setDatePremiereImmatriculation(\DateTimeInterface $date): static
    {
        $this->date_premiere_immatriculation = $date;
        return $this;
    }

    public function isEcologique(): ?bool
    {
        return $this->ecologique;
    }

    public function setEcologique(bool $ecologique): static
    {
        $this->ecologique = $ecologique;
        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(?int $nb_place): static
    {
        $this->nb_place = $nb_place;
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;
        return $this;
    }

    /**
     * @return Collection<int, Covoiturage>
     */
    public function getCovoiturages(): Collection
    {
        return $this->covoiturages;
    }

    public function addCovoiturage(Covoiturage $covoiturage): static
    {
        if (!$this->covoiturages->contains($covoiturage)) {
            $this->covoiturages->add($covoiturage);
            $covoiturage->setVoiture($this);
        }

        return $this;
    }

    public function removeCovoiturage(Covoiturage $covoiturage): static
    {
        if ($this->covoiturages->removeElement($covoiturage)) {
            if ($covoiturage->getVoiture() === $this) {
                $covoiturage->setVoiture(null);
            }
        }

        return $this;
    }
}

templates/profil/_profil_layout.html.twig
<div
	class="container my-4" style="background-color: #FBF8F7; border-radius: 15px; padding: 30px;">
	<!-- Avatar + Nom + Note -->
<div class="text-center mb-4">
{% if app.user.photo %}
	<img src="data:image/jpeg;base64,{{ app.user.photo }}" alt="Photo de profil" class="img-thumbnail rounded-circle" style="width: 120px; height: 120px; object-fit: cover;"/>
{% else %}
	<img src="{{ asset('images/avatar.png') }}" alt="Avatar par défaut" class="img-thumbnail rounded-circle" style="width: 120px; height: 120px; object-fit: cover;"/>
{% endif %}


	<h2 class="mt-3">{{ app.user.pseudo }}</h2>

	<div class="d-flex justify-content-center align-items-center gap-2">
		<span class="fs-5">
			<span class="text-success fs-4">★</span>
			{% if app.user.getNoteMoyenne() is not null %}
				{{ app.user.getNoteMoyenne() }}/5 –
			{% else %}
				Aucune note –
			{% endif %}
		</span>

		<a href="{{ path('app_profil_avis') }}" class="text-decoration-none text-success">
			{{ app.user.getAvisConducteur|length }}
			{{ app.user.getAvisConducteur|length == 1 ? 'avis' : 'avis' }}
		</a>
	</div>

	<p>
		<strong>Crédits :</strong>
		{{ app.user.credits }}
		crédits</p>
</div>



	<!-- Flash Messages -->
	{% for message in app.flashes('danger') %}
		<div class="alert alert-danger text-center">{{ message }}</div>
	{% endfor %}
	{% for message in app.flashes('success') %}
		<div class="alert alert-success text-center">{{ message }}</div>
	{% endfor %}

	<!-- Rôles -->
	<form method="post" action="{{ path('app_choix_role') }}">
		<div class="form-check">
			<input class="form-check-input" type="checkbox" value="ROLE_CHAUFFEUR" name="roles[]" id="chauffeur" {{ 'ROLE_CHAUFFEUR' in app.user.roles ? 'checked' : '' }}>
			<label class="form-check-label" for="chauffeur">Je suis chauffeur</label>
		</div>
		<div class="form-check">
			<input class="form-check-input" type="checkbox" value="ROLE_PASSAGER" name="roles[]" id="passager" {{ 'ROLE_PASSAGER' in app.user.roles ? 'checked' : '' }}>
			<label class="form-check-label" for="passager">Je suis passager</label>
		</div>

		{% if 'ROLE_CHAUFFEUR' in app.user.roles and app.user.voitures is empty %}
			<div class="alert alert-warning text-center mt-3">
				🚗 Vous avez sélectionné le rôle
				<strong>chauffeur</strong>, mais vous n'avez encore enregistré aucun véhicule.<br>
				<a href="{{ path('app_voiture_add') }}" class="btn btn-sm btn-success mt-2">Ajouter un véhicule</a>
			</div>
		{% endif %}

		<button class="btn btn-success mt-3">Mettre à jour mes rôles</button>
	</form>

	<!-- Navigation onglets -->
	<ul class="nav nav-tabs justify-content-center mb-4 border-bottom border-success">
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('app_historique') }}">Historique</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('app_profil') }}">Informations</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('covoiturage_new') }}">Créer un trajet</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('app_voiture') }}">Véhicules</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('app_preference') }}">Préférences</a>
		</li>
		<li class="nav-item">
			<a class="nav-link text-success" href="{{ path('app_mes_trajets') }}">Mes Trajets</a>
		</li>
	</ul>
</div>

templates/profil/detail_trajet.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du trajet
{% endblock %}

{% block body %}
	<div class="container py-5">
		<div class="bg-white p-4 rounded shadow-sm border border-success-subtle">
			<h2 class="text-success mb-4 text-center">Détail du trajet 🚗</h2>

			<div class="mb-4">
				<p>
					<strong>Date :</strong>
					{{ trajet.dateDepart|date('d/m/Y') }}</p>
				<p>
					<strong>Départ :</strong>
					{{ trajet.lieuDepart }}</p>
				<p>
					<strong>Arrivée :</strong>
					{{ trajet.lieuArrivee }}</p>
				<p>
					<strong>Heure :</strong>
					{{ trajet.heureDepart|date('H:i') }}
					-
					{{ trajet.heureArrivee|date('H:i') }}</p>
				<p>
					<strong>Places restantes :</strong>
					{{ trajet.nbPlace }}</p>
			</div>

			<h4 class="text-success">Liste des passagers :</h4>

			{% if passagers is empty %}
				<p class="text-muted">Aucun passager inscrit pour l'instant.</p>
			{% else %}
				<ul class="list-group">
					{% for passager in passagers %}
						<li class="list-group-item d-flex justify-content-between align-items-center">
							{{ passager.pseudo }}
							<span class="badge bg-primary">{{ passager.email }}</span>
						</li>
					{% endfor %}
				</ul>
			{% endif %}

			<div class="text-center mt-4">
				<a href="{{ path('app_mes_trajets') }}" class="btn btn-outline-secondary">⬅ Retour à mes trajets</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon profil
{% endblock %}

{% block body %}
	<div class="container py-5" style="max-width: 700px;">
		<div class="bg-white p-4 rounded shadow-sm border border-success-subtle" style="background-color: #FBF8F7;">
			<h2 class="text-center mb-4 text-success">Modifier mes informations</h2>

			{% for message in app.flashes('success') %}
				<div class="alert alert-success text-center">
					{{ message }}
				</div>
			{% endfor %}

            <script>
                // Supprime l'alerte après 3 secondes
            setTimeout(function () {
            const alert = document.querySelector('.alert');
            if (alert) {
            alert.classList.remove('show');
            alert.classList.add('fade');
            setTimeout(() => alert.remove(), 300); // Supprime complètement du DOM
            }
            }, 3000);
            </script>


            {{ form_start(form) }}
            <div class="row gy-4">
                <div class="col-md-6">
                    <div class="form-group">
                    {{ form_label(form.photo, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                    {{ form_widget(form.photo, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.pseudo, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.pseudo, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.email, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.nom, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.prenom, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.telephone, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.telephone, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form_label(form.dateNaissance, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.dateNaissance, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-group">
                        {{ form_label(form.adresse, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>

                <div class="col-12">
                    <div class="form-group">
                        {{ form_label(form.plainPassword, null, {'label_attr': {'class': 'mb-2 fw-semibold'}}) }}
                        {{ form_widget(form.plainPassword, {'attr': {'class': 'form-control'}}) }}
                    </div>
                </div>
            </div>

            <div class="text-center mt-4">
                <button type="submit" class="btn btn-success px-4">Enregistrer</button>
                <a href="{{ path('app_profil') }}" class="btn btn-outline-secondary ms-2">Annuler</a>
            </div>
            {{ form_end(form) }}


		</div>
	</div>
{% endblock %}

templates/profil/historique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil
{% endblock %}

{% block body %}
{% include 'profil/_profil_layout.html.twig' with { user: app.user } %}


	<div class="container py-5" style="max-width: 800px;">
		<div class="bg-white p-4 rounded shadow-sm border border-success-subtle" style="background-color: #FBF8F7;">
			<h2 class="mb-4 text-success text-center">Historique de mes trajets</h2>

			{% if trajetsConducteur is empty and trajetsPassager is empty %}
				<p class="text-muted text-center">Vous n'avez effectué aucun trajet pour le moment.</p>
			{% endif %}

			{% if trajetsConducteur is not empty %}
				<h4 class="text-success mb-3">
					<i class="bi bi-steering-wheel me-2"></i>En tant que conducteur
				</h4>
				<div class="list-group mb-4">
					{% for trajet in trajetsConducteur %}
						<div class="list-group-item list-group-item-action mb-2 border rounded">
							<div class="d-flex justify-content-between">
								<strong>{{ trajet.dateDepart|date('d F Y') }}</strong>
								<span class="badge bg-success">Conducteur</span>
							</div>
							<div>{{ trajet.lieuDepart }}
								→
								{{ trajet.lieuArrivee }}</div>
							<div>
								{{ trajet.heureDepart|date('H:i') }}
								-
								{{ trajet.heureArrivee|date('H:i') }}
								<small class="text-muted ms-2">{{ trajet.nbPlace }}
									place(s)</small>
							</div>
							<div class="text-muted">
								{{ trajet.prixPersonne|number_format(2, ',', '.') }}
								€
							</div>
							{% if trajet.statut == 'Annulé' %}
								<span class="badge bg-danger mt-2">Annulé</span>
							{% endif %}
						</div>
					{% endfor %}
				</div>
			{% endif %}

			{% if trajetsPassager is not empty %}
				<h4 class="text-primary mb-3">
					<i class="bi bi-person-fill me-2"></i>En tant que passager
				</h4>
				<div class="list-group">
					{% for trajet in trajetsPassager %}
						<div class="list-group-item list-group-item-action mb-2 border rounded">
							<div class="d-flex justify-content-between">
								<strong>{{ trajet.dateDepart|date('d F Y') }}</strong>
								<span class="badge bg-secondary">Passager</span>
							</div>
							<div>{{ trajet.lieuDepart }}
								→
								{{ trajet.lieuArrivee }}</div>
							<div>
								{{ trajet.heureDepart|date('H:i') }}
								-
								{{ trajet.heureArrivee|date('H:i') }}
							</div>
							<div class="text-muted">
								Conducteur :
								{{ trajet.conducteur.pseudo }}
							</div>
							{% if trajet.statut == 'Annulé' %}
								<span class="badge bg-danger mt-2">Annulé</span>
							{% endif %}
						</div>
					{% endfor %}
				</div>
			{% endif %}
		</div>
	</div>
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon Profil
{% endblock %}

{% block body %}
{% include 'profil/_profil_layout.html.twig' %}

		<!-- Bloc information -->
		<div class="bg-white p-4 rounded shadow-sm" style="border-left: 5px solid #3ba66b;">
			<div class="d-flex justify-content-between align-items-center mb-3">
				<h4 class="mb-0 fw-bold">Information personelle</h4>
                <a href="{{ path('app_profil_edit') }}" class="btn btn-outline-success btn-sm px-3">Modifier</a>
			</div>
			<div class="row">
				<div class="col-md-1 text-center">
					<i class="bi bi-person-circle" style="font-size: 3rem; color: #3ba66b;"></i>
				</div>
				<div class="col-md-11">
					<p>
						<strong>Pseudo :</strong>
						{{ user.pseudo }}</p>
					<p>
						<strong>Nom :</strong>
						{{ user.nom }}</p>
					<p>
						<strong>Prénom :</strong>
						{{ user.prenom }}</p>
					<p>
						<strong>E-mail :</strong>
						{{ user.email }}</p>
					<p>
						<strong>Téléphone :</strong>
						{{ user.telephone }}</p>
					<p>
						<strong>Date de naissance :</strong>
						{{ user.dateNaissance ? user.dateNaissance|date('d/m/Y') : 'Non renseignée' }}
					</p>

						<strong>Adresse :</strong>
						{{ user.adresse }}</p>
				</div>
			</div>
		</div>
	</div>
{% endblock %}